/* The Challenge (secret, Demon): unlocked with a Vault code. Fake spikes, dash orbs and a few dirty tricks. */
(function (root) {
  'use strict';
  const GD = root.GD;
  const { col, pulse, enter, exit, stack, spd } = GD.LH;
  GD.addLevel({
    id: 'challenge', name: 'The Challenge', diff: 'demon', stars: 10, color: '#3a3a3a', song: 'challenge',
    secret: 'challenge', secretCode: 'the challenge', secretMsg: 'So you think you are good? A secret level has appeared in the level list...',
    songDef: { name: 'The Challenge', bpm: 165, root: 50, scale: 'phrygian', prog: [0, 1, 4, 1], seed: 191, lead: 'square', bass: 'wobble', drums: 'break', arr: 'fast', loopFrom: 2 },
    settings: { bgStyle: 'grid', gStyle: 'stripes', bg: '#2a2a2a', g: '#0e0e0e', line: '#ffffff' },
    style: { main: 'block3', alt: 'block5' },
    map: [
      16,
      // fake spikes: jumping them runs into the ceiling spikes, so just run through
      `
      ....vvvvvv.....
      ...............
      ....~~~~~~.....`,
      8, '^^', 9,
      `
      ......vvvvvvv.......
      ....................
      ..^...~~~~~~~...^...`,
      10,
      col('bg', '#4a0a0a'), col('g', '#1a0404'), pulse('#ff4040'),
      // dash orbs over long pits
      `
      .......................
      .......................
      ..d....................
      .................####..
      ..^^^^^^^^^^^^^^^^^^^^^`,
      6,
      `
      ##################################
      ...........vvvvvvvvvvvvvvvv.......
      .......d..........................
      ..................................
      ..e...............................
      .........................######...
      ..^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...`,
      { t: 'coin', at: -12, y: 3 },
      8,
      // gravity dash up to the ceiling path, a blue orb brings you down again
      `
      ...............########################.
      .......................vv..........vv...
      .........................................
      ..q.....................................
      .........................................
      ..^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`,
      `
      ##########......
      ................
      ..b.............
      ................
      ................
      ^^..............`,
      8,
      col('bg', '#0a0a4a'), col('g', '#04041a'), pulse('#4040ff'),
      spd(2),
      10, '^^^', 10,
      enter('S'),
      GD.gates({ len: 48, seed: 192, gap: 3, every: 6, maxStep: 2, coinAt: 3 }),
      stack('V'),
      GD.waveRun({ len: 40, seed: 193, width: 2, open: 4 }),
      exit('C'),
      col('bg', '#2a2a2a'), col('g', '#0e0e0e'), pulse(),
      8,
      // last trick: the obvious jump is fake, the dash orb is the way
      `
      ..........................
      ..........................
      ..............$...........
      ..d.......................
      ..........................
      ..~~~^^^^^^^^^^^^^^^^^^^..`,
      8,
      spd(1),
      10, '^', 16,
    ],
  }, 'horizon');
})(typeof window !== 'undefined' ? window : globalThis);
