#!/usr/bin/env node
/* Verifies the endless-mode chunks and writes js/endless-verified.js.
 *
 *   node tools/endless-check.js            -> test every chunk at every speed and seed, write the list
 *   node tools/endless-check.js --runs 3   -> also solve 3 complete generated runs (slow)
 *   node tools/endless-check.js --only ship,wave --out part.json
 *                                          -> check some chunks only, write their results as JSON (for parallel runs)
 *   node tools/endless-check.js --merge a.json,b.json --runs 2
 *                                          -> combine such results into js/endless-verified.js (no chunk checks)
 *
 * A chunk variant is kept when the solver beats it, no click needs a window under 3 frames, no portal is
 * skipped and (for flying chunks) constant input does not get through it. */
'use strict';
const fs = require('fs');
const path = require('path');
const vm = require('vm');
const { solve, windows, portalAudit, GD } = require('./solve.js');

const ROOT = path.join(__dirname, '..');
vm.runInThisContext(fs.readFileSync(path.join(ROOT, 'js/endless.js'), 'utf8'), { filename: 'js/endless.js' });
const args = process.argv.slice(2);
const opt = (k) => (args.includes(k) ? args[args.indexOf(k) + 1] : null);
const runs = +opt('--runs') || 0;
const only = opt('--only') ? opt('--only').split(',') : null;
const outJson = opt('--out');
const merge = opt('--merge') ? opt('--merge').split(',') : null;
const SUB = 4;

let n = 0;
function check(entries, speed, flying) {
  const def = { id: 'endless-check-' + n++, name: 'chunk', map: [10, entries, 14], settings: { mode: 'cube', spd: speed } };
  const lvl = GD.buildLevel(def);
  const r = solve(lvl, {});
  if (!r.ok) return 'unsolvable';
  const w = windows(lvl, r.inputs);
  if (w.some((x) => x.win < 3)) return 'tight';
  if (portalAudit(lvl, r.inputs).length) return 'portal skipped';
  if (flying) {
    // constant input from the start must not get through
    for (const h of [0, 1]) {
      const t = new GD.World(lvl, {});
      let held = false;
      for (let f = 0; f < 60 * 60 && !t.p.dead && !t.p.done; f++) {
        // jump into the portal normally, then keep the input constant inside the flying part
        const inFly = t.p.mode !== 'cube';
        t.setHold(inFly ? !!h : held);
        for (let k = 0; k < SUB; k++) t.step();
      }
      if (t.p.done) return 'autopilot ' + (h ? 'hold' : 'idle');
    }
  }
  return 'ok';
}

const ok = {};
for (const f of merge || []) Object.assign(ok, JSON.parse(fs.readFileSync(f, 'utf8')));
for (const c of merge ? [] : GD.ENDLESS_CHUNKS) {
  if (only && !only.includes(c.id)) continue;
  for (const sp of c.speeds) {
    const seeds = c.seeded ? GD.ENDLESS_SEEDS : [0];
    const good = [], bad = {};
    for (const seed of seeds) {
      const res = check(c.make(seed, sp), sp, !!c.seeded);
      if (res === 'ok') good.push(seed);
      else bad[res] = (bad[res] || 0) + 1;
    }
    if (good.length) ok[c.id + '@' + sp] = good;
    if (outJson) fs.writeFileSync(outJson, JSON.stringify(ok)); // keep partial results of long runs
    console.log(`${good.length ? '✓' : '✗'} ${c.id}@${sp}x: ${good.length}/${seeds.length} ok ${Object.keys(bad).length ? JSON.stringify(bad) : ''}`);
  }
}
if (outJson) {
  fs.writeFileSync(outJson, JSON.stringify(ok));
  console.log(`wrote ${outJson} (${Object.keys(ok).length} variants)`);
  process.exit(0);
}
// keep the catalogue order in the generated file
const sorted = {};
for (const c of GD.ENDLESS_CHUNKS) for (let sp = 0; sp <= 4; sp++) if (ok[c.id + '@' + sp]) sorted[c.id + '@' + sp] = ok[c.id + '@' + sp];
const out = `/* Generated by tools/endless-check.js – verified endless chunk variants (chunk@speed -> seeds). Do not edit. */
(function (root) {
  root.GD.ENDLESS_OK = ${JSON.stringify(sorted)};
})(typeof window !== 'undefined' ? window : globalThis);
`;
fs.writeFileSync(path.join(ROOT, 'js/endless-verified.js'), out);
console.log(`wrote js/endless-verified.js (${Object.keys(sorted).length} variants)`);

// whole generated runs (transitions between chunks, speed changes, tier changes)
GD.ENDLESS_OK = ok;
let failed = 0;
for (let i = 0; i < runs; i++) {
  const gen = new GD.Endless(4242 + i * 7919);
  const objects = gen.until(2600);
  const lvl = { settings: Object.assign({}, GD.DEFAULT_SETTINGS, { mode: 'cube', spd: 1 }), objects };
  const t0 = Date.now();
  const r = solve(lvl, {});
  if (!r.ok) failed++;
  console.log(`${r.ok ? '✓' : '✗'} run ${i + 1}: ${gen.count} chunks, ${gen.col} blocks${r.ok ? '' : ', stuck at block ' + (r.bestX / 30).toFixed(0)} [${((Date.now() - t0) / 1000).toFixed(0)}s]`);
}
process.exit(failed ? 1 : 0);
